<%@ Page Language="C#" MasterPageFile="~/admin/admin.master" AutoEventWireup="true" CodeFile="Admin.aspx.cs" Inherits="User_controls_PicasaSlideShow_Admin" %>
<asp:Content ID="Content1" ContentPlaceHolderID="cphAdmin" Runat="Server">

<div class="content-box-outer">
    <div class="content-box-full">

<div class="settingsxx">
    <h1>Settings: Picasa Web Albums and Slide Show</h1>
    <div id="formContainer" runat="server" class="mgr">
        <div class="info" style="float: right; width: 350px;">
            Copy tag(s) generated by extension to any place in the post or page.<br />
            Extension will transform this tag into Picasa Album or Slide Show. 
        </div>
        
        <div id="spamExtension" style="width:350px; padding:5px; margin-bottom:5px;">
            <table style="padding:0;margin:0">
                <tr>
                    <td>Gmail Account</td>
                    <td><asp:TextBox ID="txtGMail" runat="server" MaxLength="50"></asp:TextBox></td>
                    <td>@Gmail.com</td>
                </tr>
                <tr>
                    <td><span>Password</span> &nbsp;&nbsp;</td>
                    <td colspan="2"><asp:TextBox ID="txtPwd" TextMode="Password" runat="server" MaxLength="20"></asp:TextBox></td>
                </tr>
                <tr>
                    <td>Slide Show Width</td>
                    <td colspan="2"><asp:TextBox ID="txtShowWidth" runat="server" MaxLength="20"></asp:TextBox></td>
                </tr>
                <tr>
                    <td>Thumbnail Width</td>
                    <td colspan="2"><asp:DropDownList ID="ddWidth" runat="server"></asp:DropDownList></td>
                </tr>
                <tr>
                    <td style="padding:0 5px 0 0">Auto Play</td>
                    <td colspan="2"><asp:CheckBox ID="chkAuto" runat="server" BorderStyle="none" /></td>
                </tr>
            </table>        
        </div>
            
        <div style="margin-left:0">
            <asp:Button ID="btnSave" class="btn primary" runat="server" onclick="BtnSaveClick" />
            <%=Resources.labels.or %>
            <a href="~/admin/Extension Manager/default.aspx" runat="server"><%=Resources.labels.cancel %></a>
        </div>
    </div>
</div>

<div runat="server" id="list_comments" class="settings">
  <div class="mgr">  
    <h2>Your Photo Albums</h2>

    <asp:Literal ID="litContent" runat="server"></asp:Literal>
  </div>
</div>

    </div>
</div>

</asp:Content>